name: Code Formatting checks and Testing

on:
    push:
    pull_request:
jobs:
    linting-and-unit-testing:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run Code Formatting Checks
              run: pnpm lint
            
            - name: Run Unit Tests
              run: pnpm test
    end-to-end-testing:
      needs: [linting-and-unit-testing]
      runs-on: ubuntu-22.04
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install pnpm
            run: npm install -g pnpm@8
          - name: Get pnpm store directory
            shell: bash
            run: |
              echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          - name: Setup pnpm cache
            uses: actions/cache@v4
            with:
              path: ${{ env.STORE_PATH }}
              key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
              restore-keys: |
                ${{ runner.os }}-pnpm-store-
          - name: Cypress run
            uses: cypress-io/github-action@v6       
            with:
              browser: chrome
              build: pnpm build
              start: pnpm start
            env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
              BLOB_READ_WRITE_TOKE: ${{ secrets.BLOB_READ_WRITE_TOKE }}
              NEXT_PUBLIC_MAP_KEY: ${{ secrets.NEXT_PUBLIC_MAP_KEY }}              
              STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
              NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
              NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}